// <auto-generated />
using System;
using Exercice04_ContactsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercice04_ContactsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240206142716_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContactContactsList", b =>
                {
                    b.Property<int>("ContactsId")
                        .HasColumnType("int");

                    b.Property<int>("ContactsListsId")
                        .HasColumnType("int");

                    b.HasKey("ContactsId", "ContactsListsId");

                    b.HasIndex("ContactsListsId");

                    b.ToTable("ContactContactsList");
                });

            modelBuilder.Entity("Exercice04_ContactsAPI.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AvatarURL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("avatarURL");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthdate");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("firstname");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.ToTable("contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarURL = "",
                            BirthDate = new DateTime(1981, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Jean",
                            Gender = 1,
                            Lastname = "DUPONT"
                        },
                        new
                        {
                            Id = 2,
                            AvatarURL = "",
                            BirthDate = new DateTime(1993, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Jane",
                            Gender = 2,
                            Lastname = "SMITH"
                        });
                });

            modelBuilder.Entity("Exercice04_ContactsAPI.Models.ContactContactsList", b =>
                {
                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<int>("ContactsListId")
                        .HasColumnType("int")
                        .HasColumnName("contacts_list_id");

                    b.HasKey("ContactId", "ContactsListId");

                    b.HasIndex("ContactsListId");

                    b.ToTable("contact_contacts_list", (string)null);

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            ContactsListId = 1
                        },
                        new
                        {
                            ContactId = 1,
                            ContactsListId = 2
                        },
                        new
                        {
                            ContactId = 2,
                            ContactsListId = 2
                        });
                });

            modelBuilder.Entity("Exercice04_ContactsAPI.Models.ContactsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("contacts_list");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mes amis"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mes collègues"
                        });
                });

            modelBuilder.Entity("ContactContactsList", b =>
                {
                    b.HasOne("Exercice04_ContactsAPI.Models.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exercice04_ContactsAPI.Models.ContactsList", null)
                        .WithMany()
                        .HasForeignKey("ContactsListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exercice04_ContactsAPI.Models.ContactContactsList", b =>
                {
                    b.HasOne("Exercice04_ContactsAPI.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exercice04_ContactsAPI.Models.ContactsList", "ContactsList")
                        .WithMany()
                        .HasForeignKey("ContactsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("ContactsList");
                });
#pragma warning restore 612, 618
        }
    }
}
